// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKV27RVe5c5ixW2Z2YVjpCvxhWXcyU6P0',
    appId: '1:913221160951:web:02b68b82a9602b7cd628f2',
    messagingSenderId: '913221160951',
    projectId: 'chatbot-8cb7f',
    authDomain: 'chatbot-8cb7f.firebaseapp.com',
    storageBucket: 'chatbot-8cb7f.appspot.com',
    measurementId: 'G-SH7NME26DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy1Y6A0Cyg-FzJBK_jkljBPehL2c_g7Bs',
    appId: '1:913221160951:android:a2563b69ba0a653cd628f2',
    messagingSenderId: '913221160951',
    projectId: 'chatbot-8cb7f',
    storageBucket: 'chatbot-8cb7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsHchc3hYXuNSXJwK3uYFsoZyJcaw4iFM',
    appId: '1:913221160951:ios:c309cc1d634efbd7d628f2',
    messagingSenderId: '913221160951',
    projectId: 'chatbot-8cb7f',
    storageBucket: 'chatbot-8cb7f.appspot.com',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsHchc3hYXuNSXJwK3uYFsoZyJcaw4iFM',
    appId: '1:913221160951:ios:c309cc1d634efbd7d628f2',
    messagingSenderId: '913221160951',
    projectId: 'chatbot-8cb7f',
    storageBucket: 'chatbot-8cb7f.appspot.com',
    iosBundleId: 'com.example.chatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKV27RVe5c5ixW2Z2YVjpCvxhWXcyU6P0',
    appId: '1:913221160951:web:4e279985ba41878cd628f2',
    messagingSenderId: '913221160951',
    projectId: 'chatbot-8cb7f',
    authDomain: 'chatbot-8cb7f.firebaseapp.com',
    storageBucket: 'chatbot-8cb7f.appspot.com',
    measurementId: 'G-1NH13MRTKB',
  );
}
